# 1. Парсинг данных с сайта - https://rkn.gov.ru/activity/connection/register/license/

In [13]:
pip install selenium pandas

Requirement already satisfied: selenium in c:\users\vasiliva\anaconda3\lib\site-packages (4.16.0)
Requirement already satisfied: pandas in c:\users\vasiliva\anaconda3\lib\site-packages (1.4.2)
Requirement already satisfied: trio-websocket~=0.9 in c:\users\vasiliva\anaconda3\lib\site-packages (from selenium) (0.11.1)
Requirement already satisfied: trio~=0.17 in c:\users\vasiliva\anaconda3\lib\site-packages (from selenium) (0.23.2)
Requirement already satisfied: certifi>=2021.10.8 in c:\users\vasiliva\anaconda3\lib\site-packages (from selenium) (2021.10.8)
Requirement already satisfied: urllib3[socks]<3,>=1.26 in c:\users\vasiliva\anaconda3\lib\site-packages (from selenium) (1.26.9)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\vasiliva\anaconda3\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: numpy>=1.18.5 in c:\users\vasiliva\anaconda3\lib\site-packages (from pandas) (1.21.5)
Requirement already satisfied: pytz>=2020.1 in c:\users\vasiliva\anaconda3\lib\site-packages (from pandas) (2021.3)
Requirement already satisfied: six>=1.5 in c:\users\vasiliva\anaconda3\lib\site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)
Requirement already satisfied: outcome in c:\users\vasiliva\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.3.0.post0)
Requirement already satisfied: sniffio>=1.3.0 in c:\users\vasiliva\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.3.0)
Requirement already satisfied: cffi>=1.14 in c:\users\vasiliva\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.15.0)
Requirement already satisfied: exceptiongroup in c:\users\vasiliva\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.1.3)
Requirement already satisfied: sortedcontainers in c:\users\vasiliva\anaconda3\lib\site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: attrs>=20.1.0 in c:\users\vasiliva\anaconda3\lib\site-packages (from trio~=0.17->selenium) (23.1.0)
Requirement already satisfied: idna in c:\users\vasiliva\anaconda3\lib\site-packages (from trio~=0.17->selenium) (3.3)
Requirement already satisfied: pycparser in c:\users\vasiliva\anaconda3\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.21)
Requirement already satisfied: wsproto>=0.14 in c:\users\vasiliva\anaconda3\lib\site-packages (from trio-websocket~=0.9->selenium) (1.2.0)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in c:\users\vasiliva\anaconda3\lib\site-packages (from urllib3[socks]<3,>=1.26->selenium) (1.7.1)
Requirement already satisfied: h11<1,>=0.9.0 in c:\users\vasiliva\anaconda3\lib\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.14.0)
Note: you may need to restart the kernel to use updated packages.

In [117]:
from selenium import webdriver
from selenium.webdriver.common.by import By
import pandas as pd
import time
import re

In [17]:
# Настройка браузера
options = webdriver.ChromeOptions()
options.add_argument('--start-maximized')
driver = webdriver.Chrome(options=options)

In [65]:
# Забираем ссылки на карточки (со всех листов)

base_url = "https://rkn.gov.ru/activity/connection/register/license/p"
page_number = 0  # начинаем с нуля

all_links = []

while True:
    url = f"{base_url}{page_number}/"
    print(f"Страница в работе: p{page_number}")

    driver.get(url)
    time.sleep(1)

    licenses = driver.find_elements(By.CSS_SELECTOR, 'tr.clmn1, tr.clmn2')

    if not licenses:
        print(f"Страница p{page_number} пуста. Останавливаемся.")
        break

    for lic in licenses:
        try:
            link = lic.find_element(By.TAG_NAME, 'a').get_attribute('href')
            all_links.append(link)
        except Exception as e:
            print(f"Ошибка при сборе ссылки: {e}")

    page_number += 100  # прибавляем 100 для следующей страницы

Страница в работе: p0
Страница в работе: p100
Страница в работе: p200
Страница в работе: p300
Страница в работе: p400
Страница в работе: p500
Страница в работе: p600
Страница в работе: p700
Страница в работе: p800
Страница в работе: p900
Страница в работе: p1000
Страница в работе: p1100
Страница в работе: p1200
Страница в работе: p1300
Страница в работе: p1400
Страница в работе: p1500
Страница в работе: p1600
Страница в работе: p1700
Страница в работе: p1800
Страница в работе: p1900
Страница в работе: p2000
Страница в работе: p2100
Страница в работе: p2200
Страница в работе: p2300
Страница в работе: p2400
Страница в работе: p2500
Страница в работе: p2600
Страница в работе: p2700
Страница в работе: p2800
Страница в работе: p2900
Страница в работе: p3000
Страница в работе: p3100
Страница в работе: p3200
Страница в работе: p3300
Страница в работе: p3400
Страница в работе: p3500
Страница в работе: p3600
Страница в работе: p3700
Страница в работе: p3800
Страница в работе: p3900
Страница в работе: p4000
Страница в работе: p4100
Страница в работе: p4200
Страница в работе: p4300
Страница в работе: p4400
Страница в работе: p4500
Страница в работе: p4600
Страница в работе: p4700
Страница в работе: p4800
Страница в работе: p4900
Страница в работе: p5000
Страница в работе: p5100
Страница в работе: p5200
Страница в работе: p5300
Страница в работе: p5400
Страница в работе: p5500
Страница в работе: p5600
Страница в работе: p5700
Страница в работе: p5800
Страница в работе: p5900
Страница в работе: p6000
Страница в работе: p6100
Страница в работе: p6200
Страница в работе: p6300
Страница в работе: p6400
Страница в работе: p6500
Страница в работе: p6600
Страница в работе: p6700
Страница в работе: p6800
Страница в работе: p6900
Страница в работе: p7000
Страница в работе: p7100
Страница в работе: p7200
Страница в работе: p7300
Страница в работе: p7400
Страница в работе: p7500
Страница в работе: p7600
Страница в работе: p7700
Страница в работе: p7800
Страница в работе: p7900
Страница в работе: p8000
Страница в работе: p8100
Страница в работе: p8200
Страница в работе: p8300
Страница в работе: p8400
Страница в работе: p8500
Страница в работе: p8600
Страница в работе: p8700
Страница в работе: p8800
Страница в работе: p8900
Страница в работе: p9000
Страница в работе: p9100
Страница в работе: p9200
Страница в работе: p9300
Страница в работе: p9400
Страница в работе: p9500
Страница в работе: p9600
Страница в работе: p9700
Страница в работе: p9800
Страница в работе: p9900
Страница в работе: p10000
Страница в работе: p10100
Страница в работе: p10200
Страница в работе: p10300
Страница в работе: p10400
Страница в работе: p10500
Страница в работе: p10600
Страница в работе: p10700
Страница в работе: p10800
Страница в работе: p10900
Страница в работе: p11000
Страница в работе: p11100
Страница в работе: p11200
Страница в работе: p11300
Страница в работе: p11400
Страница в работе: p11500
Страница в работе: p11600
Страница в работе: p11700
Страница в работе: p11800
Страница в работе: p11900
Страница в работе: p12000
Страница в работе: p12100
Страница в работе: p12200
Страница в работе: p12300
Страница в работе: p12400
Страница в работе: p12500
Страница в работе: p12600
Страница в работе: p12700
Страница в работе: p12800
Страница в работе: p12900
Страница в работе: p13000
Страница в работе: p13100
Страница в работе: p13200
Страница в работе: p13300
Страница в работе: p13400
Страница в работе: p13500
Страница в работе: p13600
Страница в работе: p13700
Страница в работе: p13800
Страница в работе: p13900
Страница в работе: p14000
Страница в работе: p14100
Страница в работе: p14200
Страница в работе: p14300
Страница в работе: p14400
Страница в работе: p14500
Страница в работе: p14600
Страница в работе: p14700
Страница в работе: p14800
Страница в работе: p14900
Страница в работе: p15000
Страница в работе: p15100
Страница в работе: p15200
Страница в работе: p15300
Страница в работе: p15400
Страница в работе: p15500
Страница в работе: p15600
Страница в работе: p15700
Страница в работе: p15800
Страница в работе: p15900
Страница в работе: p16000
Страница в работе: p16100
Страница в работе: p16200
Страница в работе: p16300
Страница в работе: p16400
Страница в работе: p16500
Страница в работе: p16600
Страница в работе: p16700
Страница в работе: p16800
Страница в работе: p16900
Страница в работе: p17000
Страница в работе: p17100
Страница в работе: p17200
Страница в работе: p17300
Страница в работе: p17400
Страница в работе: p17500
Страница в работе: p17600
Страница в работе: p17700
Страница в работе: p17800
Страница в работе: p17900
Страница в работе: p18000
Страница в работе: p18100
Страница в работе: p18200
Страница в работе: p18300
Страница в работе: p18400
Страница в работе: p18500
Страница в работе: p18600
Страница в работе: p18700
Страница в работе: p18800
Страница в работе: p18900
Страница в работе: p19000
Страница в работе: p19100
Страница в работе: p19200
Страница в работе: p19300
Страница в работе: p19400
Страница в работе: p19500
Страница в работе: p19600
Страница в работе: p19700
Страница в работе: p19800
Страница в работе: p19900
Страница в работе: p20000
Страница в работе: p20100
Страница в работе: p20200
Страница в работе: p20300
Страница в работе: p20400
Страница в работе: p20500
Страница в работе: p20600
Страница в работе: p20700
Страница в работе: p20800
Страница в работе: p20900
Страница в работе: p21000
Страница в работе: p21100
Страница в работе: p21200
Страница в работе: p21300
Страница в работе: p21400
Страница в работе: p21500
Страница в работе: p21600
Страница в работе: p21700
Страница в работе: p21800
Страница в работе: p21900
Страница в работе: p22000
Страница в работе: p22100
Страница в работе: p22200
Страница в работе: p22300
Страница в работе: p22400
Страница в работе: p22500
Страница в работе: p22600
Страница в работе: p22700
Страница в работе: p22800
Страница в работе: p22900
Страница в работе: p23000
Страница в работе: p23100
Страница в работе: p23200
Страница в работе: p23300
Страница в работе: p23400
Страница в работе: p23500
Страница в работе: p23600
Страница в работе: p23700
Страница в работе: p23800
Страница в работе: p23900
Страница в работе: p24000
Страница в работе: p24100
Страница в работе: p24200
Страница в работе: p24300
Страница в работе: p24400
Страница в работе: p24500
Страница в работе: p24600
Страница в работе: p24700
Страница в работе: p24800
Страница в работе: p24900
Страница в работе: p25000
Страница в работе: p25100
Страница в работе: p25200
Страница в работе: p25300
Страница в работе: p25400
Страница в работе: p25500
Страница в работе: p25600
Страница в работе: p25700
Страница в работе: p25800
Страница в работе: p25900
Страница в работе: p26000
Страница в работе: p26100
Страница в работе: p26200
Страница в работе: p26300
Страница p26300 пуста. Останавливаемся.

In [68]:
# Собираем информацию с карточек 

data = []

total_links = len(all_links)  # всего ссылок

print(f"Всего лицензий для обработки: {total_links}")

for idx, link in enumerate(all_links, 1):  # enumerate даёт номер итерации
    print(f"Обрабатываю {idx}/{total_links}: {link}")  # вывод прогресса

    driver.execute_script("window.open(arguments[0]);", link)
    driver.switch_to.window(driver.window_handles[1])

    try:
        time.sleep(1)  # ждём загрузку карточки

        # Находим ВСЕ строки в таблице
        rows = driver.find_elements(By.CSS_SELECTOR, 'table.TblList tr')
        record = {}

        for row in rows:
            tds = row.find_elements(By.TAG_NAME, 'td')
            if len(tds) >= 2:
                key = tds[0].text.strip()  # Первая ячейка — название поля
                value = tds[1].text.strip()  # Вторая ячейка — значение поля
                record[key] = value

        if record:
            data.append(record)

    except Exception as e:
        print(f"Ошибка при парсинге карточки: {e}")

    # Закрываем вкладку карточки
    driver.close()
    driver.switch_to.window(driver.window_handles[0])

Всего лицензий для обработки: 26229
Обрабатываю 1/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F00070257
Обрабатываю 2/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F00073326
Обрабатываю 3/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F00069417
Обрабатываю 4/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F00070479
Обрабатываю 5/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F00072310
Обрабатываю 6/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F00083561
Обрабатываю 7/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F00083562
Обрабатываю 8/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F00077959
Обрабатываю 9/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F00050059
Обрабатываю 10/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F00050060
Обрабатываю 11/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F00076772
Обрабатываю 12/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F00077164
Обрабатываю 13/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F01371549
Обрабатываю 14/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F01371554
Обрабатываю 15/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F00632140
Обрабатываю 16/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F00002947
Обрабатываю 17/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F00053031
Обрабатываю 18/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F00053032
Обрабатываю 19/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F00053033
Обрабатываю 20/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F00066860
Обрабатываю 21/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F00077355
Обрабатываю 22/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F00079895
Обрабатываю 23/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F00070630
Обрабатываю 24/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F00641066
Обрабатываю 25/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F00068694
Обрабатываю 26/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F00081894
Обрабатываю 27/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F00082067
Обрабатываю 28/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F00076871
Обрабатываю 29/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F00076872
Обрабатываю 30/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F00108404
Обрабатываю 31/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F01541838
Обрабатываю 32/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F01971485
Обрабатываю 33/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F00058506
Обрабатываю 34/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F00077354
Обрабатываю 35/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F00054233
Обрабатываю 36/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F00609483
Обрабатываю 37/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F00071250
Обрабатываю 38/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F00070288
Обрабатываю 39/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F00050763
Обрабатываю 40/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F00049622
Обрабатываю 41/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F00737615
Обрабатываю 42/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F00070221
Обрабатываю 43/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F00071140
Обрабатываю 44/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F00063876
Обрабатываю 45/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F00077893
Обрабатываю 46/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F00071368
Обрабатываю 47/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F00070572
Обрабатываю 48/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F00056617
Обрабатываю 49/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F00068054
Обрабатываю 50/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F00078903
Обрабатываю 51/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F00078904
Обрабатываю 52/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F00001337
Обрабатываю 53/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F00111012
Обрабатываю 54/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F00152184
Обрабатываю 55/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F00054508
Обрабатываю 56/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F00055041
Обрабатываю 57/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F00061167
Обрабатываю 58/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F00077310
Обрабатываю 59/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F00077311
Обрабатываю 60/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F00755162
Обрабатываю 61/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F00755172
Обрабатываю 62/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F00755178
Обрабатываю 63/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F00755184
Обрабатываю 64/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F00054224
Обрабатываю 65/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F00062044
Обрабатываю 66/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F00062084
Обрабатываю 67/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F00062085
Обрабатываю 68/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F00062086
Обрабатываю 69/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F00063803
Обрабатываю 70/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F00069434
Обрабатываю 71/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F00078637
Обрабатываю 72/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F00082761
Обрабатываю 73/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F00648880
Обрабатываю 74/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F00067816
Обрабатываю 75/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F00067817
Обрабатываю 76/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F00067818
Обрабатываю 77/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F00078346
Обрабатываю 78/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F00078347
Обрабатываю 79/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F00078550
Обрабатываю 80/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F00078551
Обрабатываю 81/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F00051672
Обрабатываю 82/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F00087740
Обрабатываю 83/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F00145681
Обрабатываю 84/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F00629578
Обрабатываю 85/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F00629606
Обрабатываю 86/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F00629618
Обрабатываю 87/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F00629639
Обрабатываю 88/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F00629642
Обрабатываю 89/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F00052543
Обрабатываю 90/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F00052545
Обрабатываю 91/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F00052547
Обрабатываю 92/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F00052549
Обрабатываю 93/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F00069405
Обрабатываю 94/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F00629579
Обрабатываю 95/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F00629599
Обрабатываю 96/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F00629619
Обрабатываю 97/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F00629658
Обрабатываю 98/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F00629659
Обрабатываю 99/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F00069217
Обрабатываю 100/26229: https://rkn.gov.ru/activity/connection/register/license/p0/?id=%D0%9B030-00114-77%2F00676778
Обрабатываю 101/26229: https://rkn.gov.ru/activity/connection/register/license/p100/?id=%D0%9B030-00114-77%2F00676787
Обрабатываю 102/26229: https://rkn.gov.ru/activity/connection/register/license/p100/?id=%D0%9B030-00114-77%2F00676814
Обрабатываю 103/26229: https://rkn.gov.ru/activity/connection/register/license/p100/?id=%D0%9B030-00114-77%2F00072297
Обрабатываю 104/26229: https://rkn.gov.ru/activity/connection/register/license/p100/?id=%D0%9B030-00114-77%2F00625903
Обрабатываю 105/26229: https://rkn.gov.ru/activity/connection/register/license/p100/?id=%D0%9B030-00114-77%2F00625911
Обрабатываю 106/26229: https://rkn.gov.ru/activity/connection/register/license/p100/?id=%D0%9B030-00114-77%2F00625918
Обрабатываю 107/26229: https://rkn.gov.ru/activity/connection/register/license/p100/?id=%D0%9B030-00114-77%2F00625932
Обрабатываю 108/26229: https://rkn.gov.ru/activity/connection/register/license/p100/?id=%D0%9B030-00114-77%2F00625934
Обрабатываю 109/26229: https://rkn.gov.ru/activity/connection/register/license/p100/?id=%D0%9B030-00114-77%2F00625962
Обрабатываю 110/26229: https://rkn.gov.ru/activity/connection/register/license/p100/?id=%D0%9B030-00114-77%2F00651168
Обрабатываю 111/26229: https://rkn.gov.ru/activity/connection/register/license/p100/?id=%D0%9B030-00114-77%2F00070885
Обрабатываю 112/26229: https://rkn.gov.ru/activity/connection/register/license/p100/?id=%D0%9B030-00114-77%2F00070886
Обрабатываю 113/26229: https://rkn.gov.ru/activity/connection/register/license/p100/?id=%D0%9B030-00114-77%2F00070887
Обрабатываю 114/26229: https://rkn.gov.ru/activity/connection/register/license/p100/?id=%D0%9B030-00114-77%2F00070888
Обрабатываю 115/26229: https://rkn.gov.ru/activity/connection/register/license/p100/?id=%D0%9B030-00114-77%2F00073748
Обрабатываю 116/26229: https://rkn.gov.ru/activity/connection/register/license/p100/?id=%D0%9B030-00114-77%2F00075455
Обрабатываю 117/26229: https://rkn.gov.ru/activity/connection/register/license/p100/?id=%D0%9B030-00114-77%2F00069969
Обрабатываю 118/26229: https://rkn.gov.ru/activity/connection/register/license/p100/?id=%D0%9B030-00114-77%2F00070644
Обрабатываю 119/26229: https://rkn.gov.ru/activity/connection/register/license/p100/?id=%D0%9B030-00114-77%2F00070645
Обрабатываю 120/26229: https://rkn.gov.ru/activity/connection/register/license/p100/?id=%D0%9B030-00114-77%2F00070646
Обрабатываю 121/26229: https://rkn.gov.ru/activity/connection/register/license/p100/?id=%D0%9B030-00114-77%2F00070647
Обрабатываю 122/26229: https://rkn.gov.ru/activity/connection/register/license/p100/?id=%D0%9B030-00114-77%2F00054609
Обрабатываю 123/26229: https://rkn.gov.ru/activity/connection/register/license/p100/?id=%D0%9B030-00114-77%2F00062045
Обрабатываю 124/26229: https://rkn.gov.ru/activity/connection/register/license/p100/?id=%D0%9B030-00114-77%2F00065017
Обрабатываю 125/26229: https://rkn.gov.ru/activity/connection/register/license/p100/?id=%D0%9B030-00114-77%2F00065019
Обрабатываю 126/26229: https://rkn.gov.ru/activity/connection/register/license/p100/?id=%D0%9B030-00114-77%2F00065021
Обрабатываю 127/26229: https://rkn.gov.ru/activity/connection/register/license/p100/?id=%D0%9B030-00114-77%2F00077016
Обрабатываю 128/26229: https://rkn.gov.ru/activity/connection/register/license/p100/?id=%D0%9B030-00114-77%2F00077017
Обрабатываю 129/26229: https://rkn.gov.ru/activity/connection/register/license/p100/?id=%D0%9B030-00114-77%2F00054784
Обрабатываю 130/26229: https://rkn.gov.ru/activity/connection/register/license/p100/?id=%D0%9B030-00114-77%2F00070937
Обрабатываю 131/26229: https://rkn.gov.ru/activity/connection/register/license/p100/?id=%D0%9B030-00114-77%2F00070938
Обрабатываю 132/26229: https://rkn.gov.ru/activity/connection/register/license/p100/?id=%D0%9B030-00114-77%2F00050642
Обрабатываю 133/26229: https://rkn.gov.ru/activity/connection/register/license/p100/?id=%D0%9B030-00114-77%2F00054228
Обрабатываю 134/26229: https://rkn.gov.ru/activity/connection/register/license/p100/?id=%D0%9B030-00114-77%2F00054229
Обрабатываю 135/26229: https://rkn.gov.ru/activity/connection/register/license/p100/?id=%D0%9B030-00114-77%2F00054230
Обрабатываю 136/26229: https://rkn.gov.ru/activity/connection/register/license/p100/?id=%D0%9B030-00114-77%2F00054231
Обрабатываю 137/26229: https://rkn.gov.ru/activity/connection/register/license/p100/?id=%D0%9B030-00114-77%2F00057210
Обрабатываю 138/26229: https://rkn.gov.ru/activity/connection/register/license/p100/?id=%D0%9B030-00114-77%2F00059952
Обрабатываю 139/26229: https://rkn.gov.ru/activity/connection/register/license/p100/?id=%D0%9B030-00114-77%2F00065531
Обрабатываю 140/26229: https://rkn.gov.ru/activity/connection/register/license/p100/?id=%D0%9B030-00114-77%2F00066548
Обрабатываю 141/26229: https://rkn.gov.ru/activity/connection/register/license/p100/?id=%D0%9B030-00114-77%2F00050779
Обрабатываю 142/26229: https://rkn.gov.ru/activity/connection/register/license/p100/?id=%D0%9B030-00114-77%2F00050780
Обрабатываю 143/26229: https://rkn.gov.ru/activity/connection/register/license/p100/?id=%D0%9B030-00114-77%2F00064394
Обрабатываю 144/26229: https://rkn.gov.ru/activity/connection/register/license/p100/?id=%D0%9B030-00114-77%2F00064823
Обрабатываю 145/26229: https://rkn.gov.ru/activity/connection/register/license/p100/?id=%D0%9B030-00114-77%2F00064824
Обрабатываю 146/26229: https://rkn.gov.ru/activity/connection/register/license/p100/?id=%D0%9B030-00114-77%2F00064825
Обрабатываю 147/26229: https://rkn.gov.ru/activity/connection/register/license/p100/?id=%D0%9B030-00114-77%2F00065618
Обрабатываю 148/26229: https://rkn.gov.ru/activity/connection/register/license/p100/?id=%D0%9B030-00114-77%2F00068316
Обрабатываю 149/26229: https://rkn.gov.ru/activity/connection/register/license/p100/?id=%D0%9B030-00114-77%2F00905115
Обрабатываю 150/26229: https://rkn.gov.ru/activity/connection/register/license/p100/?id=%D0%9B030-00114-77%2F00905139
Обрабатываю 151/26229: https://rkn.gov.ru/activity/connection/register/license/p100/?id=%D0%9B030-00114-77%2F00078667
Обрабатываю 152/26229: https://rkn.gov.ru/activity/connection/register/license/p100/?id=%D0%9B030-00114-77%2F00071929
Обрабатываю 153/26229: https://rkn.gov.ru/activity/connection/register/license/p100/?id=%D0%9B030-00114-77%2F00050462
Обрабатываю 154/26229: https://rkn.gov.ru/activity/connection/register/license/p100/?id=%D0%9B030-00114-77%2F00053097
Обрабатываю 155/26229: https://rkn.gov.ru/activity/connection/register/license/p100/?id=%D0%9B030-00114-77%2F00053098
Обрабатываю 156/26229: https://rkn.gov.ru/activity/connection/register/license/p100/?id=%D0%9B030-00114-77%2F00057677
Обрабатываю 157/26229: https://rkn.gov.ru/activity/connection/register/license/p100/?id=%D0%9B030-00114-77%2F00069105
Обрабатываю 158/26229: https://rkn.gov.ru/activity/connection/register/license/p100/?id=%D0%9B030-00114-77%2F00070400
Обрабатываю 159/26229: https://rkn.gov.ru/activity/connection/register/license/p100/?id=%D0%9B030-00114-77%2F00070401
Обрабатываю 160/26229: https://rkn.gov.ru/activity/connection/register/license/p100/?id=%D0%9B030-00114-77%2F00070402
Обрабатываю 161/26229: https://rkn.gov.ru/activity/connection/register/license/p100/?id=%D0%9B030-00114-77%2F00050554
Обрабатываю 162/26229: https://rkn.gov.ru/activity/connection/register/license/p100/?id=%D0%9B030-00114-77%2F00052853
Обрабатываю 163/26229: https://rkn.gov.ru/activity/connection/register/license/p100/?id=%D0%9B030-00114-77%2F00052854
Обрабатываю 164/26229: https://rkn.gov.ru/activity/connection/register/license/p100/?id=%D0%9B030-00114-77%2F00958717
Обрабатываю 165/26229: https://rkn.gov.ru/activity/connection/register/license/p100/?id=%D0%9B030-00114-77%2F00077572
Обрабатываю 166/26229: https://rkn.gov.ru/activity/connection/register/license/p100/?id=%D0%9B030-00114-77%2F00077573
Обрабатываю 167/26229: https://rkn.gov.ru/activity/connection/register/license/p100/?id=%D0%9B030-00114-77%2F00077574
Обрабатываю 168/26229: https://rkn.gov.ru/activity/connection/register/license/p100/?id=%D0%9B030-00114-77%2F00155174
Обрабатываю 169/26229: https://rkn.gov.ru/activity/connection/register/license/p100/?id=%D0%9B030-00114-77%2F00082679
Обрабатываю 170/26229: https://rkn.gov.ru/activity/connection/register/license/p100/?id=%D0%9B030-00114-77%2F00082680
Обрабатываю 171/26229: https://rkn.gov.ru/activity/connection/register/license/p100/?id=%D0%9B030-00114-77%2F00082681

In [71]:
# переводим в df
df = pd.DataFrame(data)

In [73]:
# сохраняем в csv
df.to_csv('Лицензии.csv', index = False)

# Работа с DF. Обработка собранной информации

In [75]:
print([columns for columns in df])

['Статус лицензии', 'Наименование лицензирующего органа', 'Регистрационный номер лицензии', 'Номер лицензии, присвоенный до 01.03.2022', 'Дата предоставления лицензии', 'День начала оказания услуг', 'Срок действия до', 'Полное наименование лицензиата', 'Сокращенное наименование', 'Фирменное наименование', 'Организационно-правовая форма', 'Адрес места нахождения', 'ОГРН', 'ИНН', 'Номер телефона', 'Адрес электронной почты', 'Территория действия лицензии', 'Лицензируемый вид деятельности с указанием выполняемых работ, составляющих лицензируемый вид деятельности', 'Номер и дата лицензионного приказа о предоставлении лицензии', 'Номер и дата приказа Роскомнадзора о переоформлении лицензии', 'Номер и дата приказа Роскомнадзора о продлении срока действия лицензии', 'Номер и дата приказа Роскомнадзора о приостановлении/возобновлении действия лицензии', 'Номер и дата приказа лицензирующего органа о прекращении действия лицензии, основание и дата прекращения действия лицензии', 'Основание, дата вынесения решения суда об аннулировании лицензии и реквизиты такого решения', 'Дата вынесения решения суда об отмене вступившего в законную силу решения суда об аннулировании лицензии и реквизиты такого решения', 'Даты внесения в реестр лицензий сведений о лицензиате', 'Лицензионные требования', 'Учетный номер контрольного (надзорного) мероприятия в едином реестре контрольных (надзорных) мероприятий', 'ОГРНИП']

In [77]:
pd.set_option('display.max_columns', 500)

In [82]:
# Создаем df инфа про лицензии
df_License = df.copy()
df_License = df_License[[
    'Регистрационный номер лицензии', 'Статус лицензии', 'День начала оказания услуг', 'Срок действия до',
    'ИНН', 'Территория действия лицензии', 'Лицензируемый вид деятельности с указанием выполняемых работ, составляющих лицензируемый вид деятельности', 
]]

In [87]:
df_company = df.copy()
df_company = df_company[[
    'Полное наименование лицензиата', 'Сокращенное наименование', 'Организационно-правовая форма', 'Адрес места нахождения',
    'ОГРН', 'ИНН', 'Номер телефона', 'Адрес электронной почты'
]]

In [93]:
df_company = df_company.drop_duplicates()

In [96]:
df_License = df_License.drop_duplicates()

In [86]:
df['Фирменное наименование'].unique()

array(['', nan], dtype=object)

In [99]:
# ИНН, которых больше 1
df_company['ИНН'].value_counts().sort_values(ascending=False)

7801002274    3
1605003947    3
8602060555    3
1300012383    3
7703119524    3
             ..
7805071261    1
7706412930    1
6228049685    1
1308080160    1
9001007809    1
Name: ИНН, Length: 8938, dtype: int64

In [102]:
# Данные не разнятся. Скорее всего где-то заполнили немного подругому
df_company[df_company['ИНН'] == '1300012383']

,Полное наименование лицензиата,Сокращенное наименование,Организационно-правовая форма,Адрес места нахождения,ОГРН,ИНН,Номер телефона,Адрес электронной почты
2194,ГОСУДАРСТВЕННОЕ АВТОНОМНОЕ УЧРЕЖДЕНИЕ РЕСПУБЛИ...,"ГАУ РЕСПУБЛИКИ МОРДОВИЯ ""ЦЦР""",Государственные автономные учреждения субъекто...,"430016, РЕСПУБЛИКА МОРДОВИЯ, городской округ С...",1241300003108,1300012383,(8342)39-10-00\n[внести изменения],boa@e-mordovia.ru\n[внести изменения]
2196,ГОСУДАРСТВЕННОЕ АВТОНОМНОЕ УЧРЕЖДЕНИЕ РЕСПУБЛИ...,"ГАУ РЕСПУБЛИКИ МОРДОВИЯ ""ЦЦР""",Государственные автономные учреждения субъекто...,"430016, РЕСПУБЛИКА МОРДОВИЯ, городской округ С...",1241300003108,1300012383,(8342)39-10-00\n[внести изменения],it@e-mordovia.ru\n[внести изменения]
2197,ГОСУДАРСТВЕННОЕ АВТОНОМНОЕ УЧРЕЖДЕНИЕ РЕСПУБЛИ...,"ГАУ РЕСПУБЛИКИ МОРДОВИЯ ""ЦЦР""",Государственные автономные учреждения субъекто...,"430016, РЕСПУБЛИКА МОРДОВИЯ, городской округ С...",1241300003108,1300012383,(8342) 39-10-00\n[внести изменения],it@e-mordovia.ru\n[внести изменения]

In [103]:
# Удалим дубликаты по ИНН, чтобы не было повторяющихся
df_company = df_company.drop_duplicates(subset = ['ИНН'])

In [105]:
df_company['ИНН'].value_counts().sort_values(ascending=False)

0317002737    1
6375997049    1
2360980415    1
6027201604    1
2722999113    1
             ..
7717022723    1
5254001230    1
7423000572    1
7717127211    1
9001007809    1
Name: ИНН, Length: 8938, dtype: int64

In [108]:
# Проверяем на пустые значения
df_company.isnull().sum()

Полное наименование лицензиата      0
Сокращенное наименование          882
Организационно-правовая форма     865
Адрес места нахождения            865
ОГРН                              865
ИНН                                 0
Номер телефона                      0
Адрес электронной почты             0
dtype: int64

In [112]:
# Логика заполнения пустых. Если сокращенного наименования нет - берем полное 
# Если организационной правовой формы нет / адреса / ОГРН - "Не установлено"
df_company = df_company.copy()
df_company.loc[:, 'Сокращенное наименование'] = df_company['Сокращенное наименование'].fillna(df_company['Полное наименование лицензиата'])
df_company.loc[:, 'Организационно-правовая форма'] = df_company['Организационно-правовая форма'].fillna('Не установлено')
df_company.loc[:, 'Адрес места нахождения'] = df_company['Адрес места нахождения'].fillna('Не установлено')
df_company.loc[:, 'ОГРН'] = df_company['ОГРН'].fillna('Не установлено')

In [113]:
# повторная проверка на пустые
df_company.isnull().sum()

Полное наименование лицензиата    0
Сокращенное наименование          0
Организационно-правовая форма     0
Адрес места нахождения            0
ОГРН                              0
ИНН                               0
Номер телефона                    0
Адрес электронной почты           0
dtype: int64

In [118]:
df_company['Регион'] = df_company['Адрес места нахождения'].str.extract(r'^[^,]*,\s*([^,]+)')

In [120]:
df_company['Регион'] = df_company['Регион'].str.lower()

In [124]:
# проверяем нулевые значения. Их нужно поправить
df_company[df_company['Регион'].isnull()]['Адрес места нахождения'].unique()

array(['Не установлено'], dtype=object)

In [126]:
df_company.loc[:, 'Регион'] = df_company['Регион'].fillna('Не установлено')

In [130]:
df_company['Номер телефона'] = df_company['Номер телефона'].str.replace('\n[внести изменения]', '', regex=False)
df_company['Адрес электронной почты'] = df_company['Адрес электронной почты'].str.replace('\n[внести изменения]', '', regex=False)

In [133]:
# Проверяем на пустые значения
df_License.isnull().sum()

Регистрационный номер лицензии                                                                               0
Статус лицензии                                                                                              0
День начала оказания услуг                                                                                   0
Срок действия до                                                                                             0
ИНН                                                                                                          0
Территория действия лицензии                                                                                 0
Лицензируемый вид деятельности с указанием выполняемых работ, составляющих лицензируемый вид деятельности    0
dtype: int64

In [135]:
df_License['Территория действия лицензии'].unique()

array(['Республика Бурятия: Северобайкальск г',
       'Республика Дагестан: Дубки, Чиркей', 'Иркутская область', ...,
       'Ленинградская область: Выборгский р-н, Выборг г',
       'Свердловская область: Кушва г (п.у.п. - Кушва г, гора Малая Благодатка), Новолялинский р-н, Новая Ляля г',
       'Запорожская область: Васильевский район, город Энергодар'],
      dtype=object)

In [142]:
df_License = df_License.copy()
df_License['Регион_Лицензии'] = df_License['Территория действия лицензии'].str.extract(r'^([^:]+)')

In [144]:
df_License['Регион_Лицензии'].unique()

array(['Республика Бурятия', 'Республика Дагестан', 'Иркутская область',
       'Российская Федерация', 'Ставропольский край',
       'Калужская область; Московская область; Тульская область',
       'Московская область', 'Мурманская область',
       'Ямало-Ненецкий автономный округ', 'Москва',
       'Нижегородская область', 'Республика Татарстан (Татарстан)',
       'Самарская область', 'Тверская область', 'Хабаровский край',
       'Псковская область', 'Краснодарский край', 'Тамбовская область',
       'Кемеровская область - Кузбасс', 'Кемеровская область',
       'Челябинская область', 'Республика Хакасия',
       'Ханты-Мансийский автономный округ - Югра', 'Курская область',
       'Республика Мордовия', 'Тюменская область',
       'Чувашская Республика - Чувашия', 'Республика Саха (Якутия)',
       'Москва; Московская область', 'Сахалинская область',
       'Приморский край', 'Республика Адыгея (Адыгея)',
       'Чукотский автономный округ', 'Кировская область',
       'Санкт-Петербург', 'Байконур; Российская Федерация',
       'Красноярский край', 'Новосибирская область',
       'Новгородская область', 'Республика Башкортостан',
       'Чеченская Республика',
       'Республика Дагестан; Чеченская Республика',
       'Республика Ингушетия; Республика Северная Осетия - Алания',
       'Ростовская область', 'Ленинградская область',
       'Волгоградская область', 'Удмуртская Республика',
       'Владимирская область', 'Воронежская область',
       'Архангельская область', 'Байконур', 'Амурская область',
       'Алтайский край; Астраханская область; Белгородская область; Брянская область; Владимирская область; Вологодская область; Ивановская область; Калужская область; Кемеровская область; Кировская область; Костромская область; Красноярский край',
       'Волгоградская область; Воронежская область; Краснодарский край; Нижегородская область; Новосибирская область; Республика Башкортостан; Республика Татарстан (Татарстан); Ростовская область; Самарская область; Свердловская область; Ярославская область',
       'Ленинградская область; Республика Адыгея (Адыгея); Санкт-Петербург',
       'Кабардино-Балкарская Республика; Карачаево-Черкесская Республика; Красноярский край',
       'Калининградская область; Камчатский край; Красноярский край',
       'Амурская область; Архангельская область; Еврейская автономная область; Забайкальский край; Иркутская область; Мурманская область; Приморский край; Республика Алтай; Республика Бурятия; Республика Калмыкия; Республика Хакасия; Сахалинская область; Хабаровский край; Ханты-Мансийский автономный округ - Югра',
       'Республика Крым; Севастополь', 'Пензенская область',
       'Архангельская область; Калининградская область; Камчатский край; Красноярский край; Магаданская область; Новосибирская область; Приморский край; Республика Саха (Якутия); Сахалинская область; Хабаровский край; Чукотский автономный округ',
       'Рязанская область', 'Республика Крым', 'Свердловская область',
       'Ярославская область', 'Белгородская область', 'Пермский край',
       'Камчатский край', 'Тульская область', 'Калужская область',
       'Алтайский край', 'Вологодская область', 'Саратовская область',
       'Костромская область', 'Смоленская область',
       'Ленинградская область; Москва; Московская область; Санкт-Петербург',
       'Курганская область',
       'Иркутская область; Калининградская область; Калужская область; Краснодарский край; Красноярский край; Москва; Московская область; Нижегородская область; Новосибирская область; Приморский край; Самарская область; Санкт-Петербург; Свердловская область',
       'Орловская область',
       'Волгоградская область; Ленинградская область; Москва; Московская область; Рязанская область; Самарская область; Санкт-Петербург',
       'Волгоградская область; Иркутская область; Краснодарский край; Ленинградская область; Москва; Московская область; Нижегородская область; Новосибирская область; Пермский край; Приморский край; Республика Башкортостан; Республика Коми; Республика Татарстан (Татарстан); Ростовская область; Самарская область; Санкт-Петербург; Свердловская область; Ставропольский край; Тюменская область; Хабаровский край',
       'Москва; Московская область; Санкт-Петербург',
       'Белгородская область; Воронежская область; Курская область; Липецкая область; Орловская область; Ростовская область; Рязанская область; Саратовская область; Тульская область',
       'Белгородская область; Курская область; Московская область; Орловская область; Рязанская область; Саратовская область',
       'Воронежская область; Липецкая область; Ростовская область; Тульская область',
       'Белгородская область; Воронежская область; Курская область; Липецкая область; Москва; Московская область; Ростовская область; Тульская область',
       'Белгородская область; Воронежская область; Курская область; Липецкая область',
       'Ленинградская область; Санкт-Петербург',
       'Алтайский край; Амурская область; Архангельская область; Астраханская область; Белгородская область; Брянская область; Владимирская область; Волгоградская область; Вологодская область; Воронежская область; Еврейская автономная область; Забайкальский край; Ивановская область; Иркутская область; Кабардино-Балкарская Республика; Калининградская область; Калужская область; Камчатский край; Карачаево-Черкесская Республика; Кемеровская область - Кузбасс; Кировская область; Костромская область; Краснодарский край; Красноярский край; Курганская область; Курская область; Ленинградская область; Липецкая область; Магаданская область; Москва; Московская область; Мурманская область; Ненецкий автономный округ; Нижегородская область; Новгородская область; Новосибирская область; Омская область; Оренбургская область; Орловская область; Пензенская область; Пермский край; Приморский край; Псковская область; Республика Адыгея (Адыгея); Республика Алтай; Республика Башкортостан; Республика Бурятия; Республика Дагестан; Республика Ингушетия; Республика Калмыкия; Республика Карелия; Республика Коми; Республика Марий Эл; Республика Мордовия; Республика Саха (Якутия); Республика Северная Осетия - Алания; Республика Татарстан (Татарстан); Республика Тыва; Республика Хакасия; Ростовская область; Рязанская область; Самарская область; Санкт-Петербург; Саратовская область; Сахалинская область; Свердловская область; Смоленская область; Ставропольский край; Тамбовская область; Тверская область; Томская область; Тульская область; Тюменская область; Удмуртская Республика; Ульяновская область; Хабаровский край; Ханты-Мансийский автономный округ - Югра; Челябинская область; Чеченская Республика; Чувашская Республика - Чувашия; Чукотский автономный округ; Ямало-Ненецкий автономный округ; Ярославская область',
       'Москва; Санкт-Петербург', 'Оренбургская область',
       'Калужская область; Москва; Московская область',
       'Белгородская область; Брянская область; Владимирская область; Воронежская область; Ивановская область; Калужская область; Костромская область; Курская область; Липецкая область; Орловская область; Рязанская область; Смоленская область; Тамбовская область; Тверская область; Тульская область; Ярославская область',
       'Белгородская область; Брянская область; Владимирская область; Воронежская область; Ивановская область; Калининградская область; Калужская область; Костромская область; Курская область; Липецкая область; Орловская область; Рязанская область; Смоленская область; Тамбовская область; Тверская область; Тульская область; Ярославская область',
       'Донецкая Народная Республика; Запорожская область; Луганская Народная Республика; Республика Крым; Севастополь; Херсонская область',
       'Краснодарский край; Республика Крым; Севастополь',
       'Алтайский край; Кемеровская область - Кузбасс; Томская область',
       'Астраханская область; Волгоградская область; Карачаево-Черкесская Республика; Краснодарский край; Новосибирская область; Псковская область; Республика Адыгея (Адыгея); Республика Дагестан; Республика Ингушетия; Республика Северная Осетия - Алания; Ростовская область; Свердловская область; Ставропольский край; Чеченская Республика',
       'Оренбургская область; Республика Бурятия; Челябинская область',
       'Алтайский край; Архангельская область; Белгородская область; Вологодская область; Воронежская область; Иркутская область; Красноярский край; Ленинградская область; Мурманская область; Нижегородская область; Самарская область; Саратовская область; Ульяновская область; Хабаровский край',
       'Калининградская область; Республика Башкортостан; Республика Татарстан (Татарстан)',
       'Еврейская автономная область; Забайкальский край; Кабардино-Балкарская Республика; Камчатский край; Курганская область; Магаданская область; Московская область; Ненецкий автономный округ; Новгородская область; Республика Калмыкия; Республика Тыва; Республика Хакасия; Чукотский автономный округ; Ямало-Ненецкий автономный округ',
       'Владимирская область; Калужская область; Омская область; Приморский край; Ярославская область',
       'Пермский край; Тюменская область',
       'Амурская область; Брянская область; Ивановская область; Кемеровская область - Кузбасс; Кировская область; Костромская область; Курская область; Липецкая область; Орловская область; Пензенская область; Республика Карелия; Республика Коми; Республика Марий Эл; Республика Мордовия; Республика Саха (Якутия); Рязанская область; Сахалинская область; Смоленская область; Тамбовская область; Тверская область; Томская область; Тульская область; Удмуртская Республика; Ханты-Мансийский автономный округ - Югра; Чувашская Республика - Чувашия',
       'Архангельская область; Республика Коми',
       'Ленинградская область; Москва',
       'Ленинградская область; Москва; Московская область; Новгородская область; Тверская область',
       'Пермский край; Свердловская область; Челябинская область',
       'Пермский край; Свердловская область',
       'Пензенская область; Республика Марий Эл; Республика Мордовия; Самарская область; Саратовская область; Ульяновская область; Чувашская Республика - Чувашия',
       'Астраханская область', 'Брянская область',
       'Калининградская область', 'Томская область', 'Республика Алтай',
       'Ульяновская область', 'Кабардино-Балкарская Республика',
       'Республика Калмыкия', 'Республика Ингушетия', 'Республика Коми',
       'Республика Карелия', 'Карачаево-Черкесская Республика',
       'Республика Марий Эл', 'Республика Северная Осетия - Алания',
       'Республика Тыва', 'Еврейская автономная область',
       'Забайкальский край', 'Ивановская область', 'Липецкая область',
       'Магаданская область', 'Омская область',
       'Ненецкий автономный округ',
       'Волгоградская область; Краснодарский край; Ленинградская область; Москва; Московская область; Ростовская область; Самарская область; Санкт-Петербург',
       'Кемеровская область; Новосибирская область; Томская область',
       'Кемеровская область - Кузбасс; Новосибирская область; Томская область',
       'Донецкая Народная Республика',
       'Нижегородская область; Пензенская область; Республика Марий Эл; Республика Мордовия; Удмуртская Республика; Ульяновская область; Чувашская Республика - Чувашия',
       'Алтайский край; Амурская область; Архангельская область; Астраханская область; Белгородская область; Брянская область; Владимирская область; Волгоградская область; Вологодская область; Воронежская область; Донецкая Народная Республика; Еврейская автономная область; Забайкальский край; Запорожская область; Ивановская область; Иркутская область; Кабардино-Балкарская Республика; Калининградская область; Калужская область; Камчатский край; Карачаево-Черкесская Республика; Кемеровская область - Кузбасс; Кировская область; Костромская область; Краснодарский край; Красноярский край; Курганская область; Курская область; Ленинградская область; Липецкая область; Луганская Народная Республика; Магаданская область; Москва; Мурманская область; Ненецкий автономный округ; Новгородская область; Новосибирская область; Омская область; Оренбургская область; Орловская область; Пермский край; Приморский край; Псковская область; Республика Адыгея (Адыгея); Республика Алтай; Республика Дагестан; Республика Ингушетия; Республика Калмыкия; Республика Карелия; Республика Коми; Республика Крым; Республика Саха (Якутия); Республика Северная Осетия - Алания; Республика Татарстан (Татарстан); Республика Тыва; Республика Хакасия; Ростовская область; Рязанская область; Санкт-Петербург; Сахалинская область; Свердловская область; Севастополь; Смоленская область; Ставропольский край; Тамбовская область; Тверская область; Томская область; Тульская область; Тюменская область; Хабаровский край; Ханты-Мансийский автономный округ - Югра; Херсонская область; Челябинская область; Чеченская Республика; Чукотский автономный округ; Ямало-Ненецкий автономный округ; Ярославская область',
       'Донецкая Народная Республика; Запорожская область; Краснодарский край; Красноярский край; Луганская Народная Республика; Москва; Московская область; Нижегородская область; Оренбургская область; Пензенская область; Республика Коми; Республика Марий Эл; Республика Мордовия; Республика Татарстан (Татарстан); Свердловская область; Тюменская область; Удмуртская Республика; Ульяновская область; Ханты-Мансийский автономный округ - Югра; Херсонская область; Челябинская область; Чувашская Республика - Чувашия; Ямало-Ненецкий автономный округ',
       'Донецкая Народная Республика; Запорожская область; Красноярский край; Луганская Народная Республика; Москва; Московская область; Ненецкий автономный округ; Нижегородская область; Оренбургская область; Пензенская область; Пермский край; Республика Башкортостан; Республика Коми; Республика Марий Эл; Республика Мордовия; Республика Татарстан (Татарстан); Самарская область; Саратовская область; Свердловская область; Тюменская область; Удмуртская Республика; Ульяновская область; Ханты-Мансийский автономный округ - Югра; Херсонская область; Челябинская область; Чувашская Республика - Чувашия; Ямало-Ненецкий автономный округ',
       'Алтайский край; Амурская область; Архангельская область; Астраханская область; Байконур; Белгородская область; Брянская область; Владимирская область; Волгоградская область; Вологодская область; Воронежская область; Еврейская автономная область; Забайкальский край; Ивановская область; Иркутская область; Кабардино-Балкарская Республика; Калининградская область; Калужская область; Камчатский край; Карачаево-Черкесская Республика; Кемеровская область - Кузбасс; Кировская область; Костромская область; Краснодарский край; Курганская область; Курская область; Ленинградская область; Липецкая область; Магаданская область; Мурманская область; Новгородская область; Новосибирская область; Омская область; Орловская область; Приморский край; Псковская область; Республика Адыгея (Адыгея); Республика Алтай; Республика Бурятия; Республика Дагестан; Республика Ингушетия; Республика Калмыкия; Республика Карелия; Республика Крым; Республика Саха (Якутия); Республика Северная Осетия - Алания; Республика Тыва; Республика Хакасия; Ростовская область; Рязанская область; Санкт-Петербург; Сахалинская область; Севастополь; Смоленская область; Ставропольский край; Тамбовская область; Тверская область; Томская область; Тульская область; Хабаровский край; Чеченская Республика; Чукотский автономный округ; Ярославская область',
       'Байконур; Республика Башкортостан; Республика Бурятия; Самарская область; Саратовская область',
       'Алтайский край; Амурская область; Архангельская область; Астраханская область; Байконур; Белгородская область; Брянская область; Владимирская область; Волгоградская область; Вологодская область; Воронежская область; Еврейская автономная область; Забайкальский край; Ивановская область; Иркутская область; Кабардино-Балкарская Республика; Калининградская область; Калужская область; Камчатский край; Карачаево-Черкесская Республика; Кемеровская область - Кузбасс; Кировская область; Костромская область; Курганская область; Курская область; Ленинградская область; Липецкая область; Магаданская область; Мурманская область; Ненецкий автономный округ; Новгородская область; Новосибирская область; Омская область; Орловская область; Пермский край; Приморский край; Псковская область; Республика Адыгея (Адыгея); Республика Алтай; Республика Башкортостан; Республика Бурятия; Республика Дагестан; Республика Ингушетия; Республика Калмыкия; Республика Карелия; Республика Крым; Республика Саха (Якутия); Республика Северная Осетия - Алания; Республика Тыва; Республика Хакасия; Ростовская область; Рязанская область; Самарская область; Санкт-Петербург; Саратовская область; Сахалинская область; Севастополь; Смоленская область; Ставропольский край; Тамбовская область; Тверская область; Томская область; Тульская область; Хабаровский край; Чеченская Республика; Чукотский автономный округ; Ярославская область',
       'Ленинградская область; Москва; Московская область; Новгородская область; Санкт-Петербург; Тверская область',
       'Калининградская область; Ленинградская область; Новгородская область; Псковская область; Санкт-Петербург; Тверская область',
       'Воронежская область; Москва; Московская область',
       'Белгородская область; Брянская область; Владимирская область; Воронежская область; Ивановская область; Калужская область; Костромская область; Курская область; Липецкая область; Москва; Московская область; Орловская область; Рязанская область; Смоленская область; Тамбовская область; Тверская область; Тульская область; Ярославская область',
       'Калужская область; Москва; Московская область; Тульская область',
       'Калужская область; Липецкая область; Москва; Ярославская область',
       'Москва; Приморский край',
       'Амурская область; Еврейская автономная область; Хабаровский край',
       'Амурская область; Еврейская автономная область; Камчатский край; Приморский край; Республика Саха (Якутия); Сахалинская область; Хабаровский край',
       'Алтайский край; Амурская область; Архангельская область; Астраханская область; Белгородская область; Брянская область; Владимирская область; Волгоградская область; Вологодская область; Воронежская область; Еврейская автономная область; Забайкальский край; Ивановская область; Иркутская область; Кабардино-Балкарская Республика; Калининградская область; Калужская область; Камчатский край; Карачаево-Черкесская Республика; Кемеровская область; Кировская область; Костромская область; Краснодарский край; Красноярский край; Курганская область; Курская область; Липецкая область; Магаданская область; Мурманская область; Ненецкий автономный округ; Нижегородская область; Новгородская область; Новосибирская область; Омская область; Оренбургская область; Орловская область; Пензенская область; Пермский край; Приморский край; Псковская область; Республика Адыгея (Адыгея); Республика Алтай; Республика Башкортостан; Республика Бурятия; Республика Дагестан; Республика Ингушетия; Республика Калмыкия; Республика Карелия; Республика Коми; Республика Крым; Республика Марий Эл; Республика Мордовия; Республика Саха (Якутия); Республика Северная Осетия - Алания; Республика Татарстан (Татарстан); Республика Тыва; Республика Хакасия; Ростовская область; Рязанская область; Самарская область; Саратовская область; Сахалинская область; Свердловская область; Севастополь; Смоленская область; Ставропольский край; Тамбовская область; Тверская область; Томская область; Тульская область; Тюменская область; Удмуртская Республика; Ульяновская область; Хабаровский край; Ханты-Мансийский автономный округ - Югра; Челябинская область; Чеченская Республика; Чувашская Республика - Чувашия; Чукотский автономный округ; Ямало-Ненецкий автономный округ; Ярославская область',
       'Еврейская автономная область; Камчатский край; Магаданская область; Республика Саха (Якутия); Хабаровский край',
       'Архангельская область; Еврейская автономная область; Забайкальский край',

In [147]:
# Сделаем отдельный df для региона действия
df_License_region = df_License.copy()
df_License_region = df_License_region[[
    'Регистрационный номер лицензии', 'Регион_Лицензии'
]]

In [161]:
# разделяем чтобы один регион одна строка
df_License_region = df_License_region.copy()

df_License_region_1 = (
    df_License_region.assign(Регион_Лицензии=df_License_region['Регион_Лицензии'].str.split(';'))
    .explode('Регион_Лицензии')
)

# Убираем лишние пробелы, если есть
df_License_region_1['Регион_Лицензии'] = df_License_region_1['Регион_Лицензии'].str.strip()

In [166]:
# проверяем пустые значения
df_License[df_License['Регион_Лицензии'].isnull()]

,Регистрационный номер лицензии,Статус лицензии,День начала оказания услуг,Срок действия до,ИНН,Территория действия лицензии,"Лицензируемый вид деятельности с указанием выполняемых работ, составляющих лицензируемый вид деятельности",Регион_Лицензии
7091,Л030-00114-77/00060526,действующая,19.02.2024,20.10.2028,0914000290,,Услуги связи для целей эфирного вещания,NaN
16577,Л030-00114-77/00071859,действующая,16.12.2024,21.07.2029,5911997011,,Услуги связи для целей эфирного вещания,NaN

In [167]:
df_License_region_1.loc[:, 'Регион_Лицензии'] = df_License_region_1['Регион_Лицензии'].fillna('Не установлено')

In [ ]:
# Финальные df проекта:

# df_License_region_1 — информация о регионах действия лицензий.
# Внешний ключ — Регистрационный номер лицензии (для объединения с df_License).
# Каждая строка — отдельный регион по одной лицензии.

# df_License — информация по лицензиям (статус, даты, ИНН, вид деятельности).
# Первичный ключ — Регистрационный номер лицензии.
# Внешний ключ — ИНН (ссылается на df_company, т.е. компания, которой выдана лицензия).

# df_company — информация о компаниях (название, форма, ОГРН, ИНН и т.д.).
# Первичный ключ — ИНН.

In [173]:
df_License_region_1.to_csv('df_License_region_1.csv', index = False, sep = ';', encoding = 'cp1251')
df_License.to_csv('df_License.csv', index = False, sep = ';', encoding = 'cp1251')
df_company.to_csv('df_company.csv', index = False, sep = ';', encoding = 'cp1251')